name: Subir imagen Docker a DockerHub

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  upload-docker-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Generar la imagen
        uses: docker/build-push-action@v2
        with:
            context: .
            file: ./Dockerfile
        

      - name: Login en DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Ponerle tag v1 a la imagen
        run: docker tag springboot_app:v1 gunterelmagno/springboot_app:v1

      - name: Ponerle tag latest a la imagen
        run: docker tag springboot_app:latest gunterelmagno/springboot_app:latest

      - name: Subir imagen v1 a DockerHub
        run: docker push gunterelmagno/springboot_app:v1
      
      - name: Subir imagen latest a DockerHub
        run: docker push gunterelmagno/springboot_app:latest

      - name: Commit automatico de los cambios
        uses: stefanzweifel/git-auto-commit-action@v5