name: Subir imagen Docker a DockerHub

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  upload-docker-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Chequear el repositorio
        uses: actions/checkout@v5

      - name: Login en DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Generar la imagen
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
            context: .
            file: ./Dockerfile
            push: true
            tags: gunterelmagno/springboot_app:v1